# Movie Recommendation

# Full Code

In [19]:
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("movie_titles.csv")

df_new = df.reset_index()
output = []
user_inp_mov = input("Search a Movie : ")

sel_col = ['type','director','cast','listed_in','description']

for featuree in sel_col:
    df_new[featuree] = df_new[featuree].fillna('')
    
com_col = df_new['type']+' '+df_new['director']+' '+df_new['cast']+' '+df_new['listed_in']+' '+df_new['description']

vect = TfidfVectorizer()
vect_col_num = vect.fit_transform(com_col)

similarityy = cosine_similarity(vect_col_num)

titles = df_new['title'].tolist()

close_movies = difflib.get_close_matches(user_inp_mov,titles)

close_movie = close_movies[0]

index_pos = df_new[df_new.title == close_movie]['index'].values[0]

similarityy_score = list(enumerate(similarityy[index_pos]))

sortingg = sorted(similarityy_score, key = lambda x:x[1], reverse=True)


print("Recommended Movies")
i = 1
for moviee in sortingg:
    index = moviee[0]
    final_movies = df[df.title.index == index]['title'].values[0]
    if i<11:
        output.append(final_movies)
        print(i,".",final_movies)
        i += 1
output

Search a Movie : zombie
Recommended Movies
1 . IZombie
2 . Easy A
3 . Zombie Dumb
4 . Being Mary Jane: The Series
5 . The Umbrella Academy
6 . Encounters with Evil
7 . The Good Cop
8 . Refresh Man
9 . Bitten
10 . The School Nurse Files


['IZombie',
 'Easy A',
 'Zombie Dumb',
 'Being Mary Jane: The Series',
 'The Umbrella Academy',
 'Encounters with Evil',
 'The Good Cop',
 'Refresh Man',
 'Bitten',
 'The School Nurse Files']

# Step-Wise Execution

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.read_csv("movie_titles.csv")
df

show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1         s2  TV Show          Blood & Water              NaN   
2         s3  TV Show              Ganglands  Julien Leclercq   
3         s4  TV Show  Jailbirds New Orleans              NaN   
4         s5  TV Show           Kota Factory              NaN   
...      ...      ...                    ...              ...   
8802   s8803    Movie                 Zodiac    David Fincher   
8803   s8804  TV Show            Zombie Dumb              NaN   
8804   s8805    Movie             Zombieland  Ruben Fleischer   
8805   s8806    Movie                   Zoom     Peter Hewitt   
8806   s8807    Movie                 Zubaan      Mozez Singh   

                                                   cast        country  \
0                                                   NaN  United States   
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                   NaN            NaN   
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   
...                                                 ...            ...   
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States   
8803                                                NaN            NaN   
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States   
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States   
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India   

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min   
1     September 24, 2021          2021  TV-MA  2 Seasons   
2     September 24, 2021          2021  TV-MA   1 Season   
3     September 24, 2021          2021  TV-MA   1 Season   
4     September 24, 2021          2021  TV-MA  2 Seasons   
...                  ...           ...    ...        ...   
8802   November 20, 2019          2007      R    158 min   
8803        July 1, 2019          2018  TV-Y7  2 Seasons   
8804    November 1, 2019          2009      R     88 min   
8805    January 11, 2020          2006     PG     88 min   
8806       March 2, 2019          2015  TV-14    111 min   

                                              listed_in  \
0                                         Documentaries   
1       International TV Shows, TV Dramas, TV Mysteries   
2     Crime TV Shows, International TV Shows, TV Act...   
3                                Docuseries, Reality TV   
4     International TV Shows, Romantic TV Shows, TV ...   
...                                                 ...   
8802                     Cult Movies, Dramas, Thrillers   
8803             Kids' TV, Korean TV Shows, TV Comedies   
8804                            Comedies, Horror Movies   
8805                 Children & Family Movies, Comedies   
8806     Dramas, International Movies, Music & Musicals   

                                            description  
0     As her father nears the end of his life, filmm...  
1     After crossing paths at a party, a Cape Town t...  
2     To protect his family from a powerful drug lor...  
3     Feuds, flirtations and toilet talk go down amo...  
4     In a city of coaching centers known to train I...  
...                                                 ...  
8802  A political cartoonist, a crime reporter and a...  
8803  While living alone in a spooky town, a young g...  
8804  Looking to survive in a world taken over by zo...  
8805  Dragged from civilian life, a former superhero...  
8806  A scrappy but poor boy worms his way into a ty...  

[8807 rows x 12 columns]

Reseting the Index with new Index Column

In [4]:
df_new = df.reset_index()
df_new

index show_id     type                  title         director  \
0         0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1         1      s2  TV Show          Blood & Water              NaN   
2         2      s3  TV Show              Ganglands  Julien Leclercq   
3         3      s4  TV Show  Jailbirds New Orleans              NaN   
4         4      s5  TV Show           Kota Factory              NaN   
...     ...     ...      ...                    ...              ...   
8802   8802   s8803    Movie                 Zodiac    David Fincher   
8803   8803   s8804  TV Show            Zombie Dumb              NaN   
8804   8804   s8805    Movie             Zombieland  Ruben Fleischer   
8805   8805   s8806    Movie                   Zoom     Peter Hewitt   
8806   8806   s8807    Movie                 Zubaan      Mozez Singh   

                                                   cast        country  \
0                                                   NaN  United States   
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                   NaN            NaN   
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   
...                                                 ...            ...   
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States   
8803                                                NaN            NaN   
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States   
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States   
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India   

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min   
1     September 24, 2021          2021  TV-MA  2 Seasons   
2     September 24, 2021          2021  TV-MA   1 Season   
3     September 24, 2021          2021  TV-MA   1 Season   
4     September 24, 2021          2021  TV-MA  2 Seasons   
...                  ...           ...    ...        ...   
8802   November 20, 2019          2007      R    158 min   
8803        July 1, 2019          2018  TV-Y7  2 Seasons   
8804    November 1, 2019          2009      R     88 min   
8805    January 11, 2020          2006     PG     88 min   
8806       March 2, 2019          2015  TV-14    111 min   

                                              listed_in  \
0                                         Documentaries   
1       International TV Shows, TV Dramas, TV Mysteries   
2     Crime TV Shows, International TV Shows, TV Act...   
3                                Docuseries, Reality TV   
4     International TV Shows, Romantic TV Shows, TV ...   
...                                                 ...   
8802                     Cult Movies, Dramas, Thrillers   
8803             Kids' TV, Korean TV Shows, TV Comedies   
8804                            Comedies, Horror Movies   
8805                 Children & Family Movies, Comedies   
8806     Dramas, International Movies, Music & Musicals   

                                            description  
0     As her father nears the end of his life, filmm...  
1     After crossing paths at a party, a Cape Town t...  
2     To protect his family from a powerful drug lor...  
3     Feuds, flirtations and toilet talk go down amo...  
4     In a city of coaching centers known to train I...  
...                                                 ...  
8802  A political cartoonist, a crime reporter and a...  
8803  While living alone in a spooky town, a young g...  
8804  Looking to survive in a world taken over by zo...  
8805  Dragged from civilian life, a former superhero...  
8806  A scrappy but poor boy worms his way into a ty...  

[8807 rows x 13 columns]

In [5]:
sel_col = ['type','director','cast','listed_in','description']
print(sel_col)

['type', 'director', 'cast', 'listed_in', 'description']


In [6]:
for featuree in sel_col:
    df_new[featuree] = df_new[featuree].fillna('')

In [7]:
com_col = df_new['type']+' '+df_new['director']+' '+df_new['cast']+' '+df_new['listed_in']+' '+df_new['description']
com_col

0       Movie Kirsten Johnson  Documentaries As her fa...
1       TV Show  Ama Qamata, Khosi Ngema, Gail Mabalan...
2       TV Show Julien Leclercq Sami Bouajila, Tracy G...
3       TV Show   Docuseries, Reality TV Feuds, flirta...
4       TV Show  Mayur More, Jitendra Kumar, Ranjan Ra...
                              ...                        
8802    Movie David Fincher Mark Ruffalo, Jake Gyllenh...
8803    TV Show   Kids' TV, Korean TV Shows, TV Comedi...
8804    Movie Ruben Fleischer Jesse Eisenberg, Woody H...
8805    Movie Peter Hewitt Tim Allen, Courteney Cox, C...
8806    Movie Mozez Singh Vicky Kaushal, Sarah-Jane Di...
Length: 8807, dtype: object

Vectorizer is used to convert text data into numerical data in the range of 0,1

In [8]:
vect = TfidfVectorizer()
vect_col_num = vect.fit_transform(com_col)
print(vect_col_num)

  (0, 20809)	0.2839231228245063
  (0, 14626)	0.1689740496825454
  (0, 6159)	0.17540785225656125
  (0, 44693)	0.1373618646514721
  (0, 19174)	0.13871562957053804
  (0, 45125)	0.049977225602842075
  (0, 48040)	0.19143707113440184
  (0, 9335)	0.2620194145801572
  (0, 2136)	0.04935447543012144
  (0, 21126)	0.2620194145801572
  (0, 20682)	0.0585335521724403
  (0, 10953)	0.15299852728535862
  (0, 42314)	0.23524448762310013
  (0, 15309)	0.19317698053494456
  (0, 25729)	0.10608820631450759
  (0, 19595)	0.1426171258278709
  (0, 32018)	0.05516124201341751
  (0, 13774)	0.18873453870269108
  (0, 44666)	0.09407563115335096
  (0, 30896)	0.25714819586744925
  (0, 14931)	0.13695672613728957
  (0, 19270)	0.08716225240353921
  (0, 3047)	0.09571645077808169
  (0, 12263)	0.10468021949159816
  (0, 22237)	0.33576854743063456
  :	:
  (8806, 14640)	0.156160921881928
  (8806, 27082)	0.1464674497256493
  (8806, 23185)	0.15049630453183677
  (8806, 450)	0.09811698614288791
  (8806, 6266)	0.11397107394269132
  (88

Finding similarity of vectorizer data

In [9]:
similarity = cosine_similarity(vect_col_num)
print(similarity)

[[1.         0.00510423 0.02015937 ... 0.01075263 0.01561066 0.03109849]
 [0.00510423 1.         0.03277887 ... 0.00102456 0.         0.00265722]
 [0.02015937 0.03277887 1.         ... 0.00553754 0.0102637  0.03030349]
 ...
 [0.01075263 0.00102456 0.00553754 ... 1.         0.05682406 0.00603679]
 [0.01561066 0.         0.0102637  ... 0.05682406 1.         0.0104643 ]
 [0.03109849 0.00265722 0.03030349 ... 0.00603679 0.0104643  1.        ]]


In [10]:
titles = df_new['title'].tolist()
print(titles)

['Dick Johnson Is Dead', 'Blood & Water', 'Ganglands', 'Jailbirds New Orleans', 'Kota Factory', 'Midnight Mass', 'My Little Pony: A New Generation', 'Sankofa', 'The Great British Baking Show', 'The Starling', 'Vendetta: Truth, Lies and The Mafia', 'Bangkok Breaking', 'Je Suis Karl', 'Confessions of an Invisible Girl', 'Crime Stories: India Detectives', 'Dear White People', "Europe's Most Dangerous Man: Otto Skorzeny in Spain", 'Falsa identidad', 'Intrusion', 'Jaguar', 'Monsters Inside: The 24 Faces of Billy Milligan', 'Resurrection: Ertugrul', 'Avvai Shanmughi', 'Go! Go! Cory Carson: Chrissy Takes the Wheel', 'Jeans', 'Love on the Spectrum', 'Minsara Kanavu', 'Grown Ups', 'Dark Skies', 'Paranoia', 'Ankahi Kahaniya', 'Chicago Party Aunt', 'Sex Education', 'Squid Game', 'Tayo and Little Wizards', 'The Father Who Moves Mountains', 'The Stronghold', 'Angry Birds', 'Birth of the Dragon', 'Chhota Bheem', 'He-Man and the Masters of the Universe', 'Jaws', 'Jaws 2', 'Jaws 3', 'Jaws: The Revenge

In [12]:
user_inp_mov = input("Search a Movie : ")

Search a Movie : zombie


In [13]:
close_movies = difflib.get_close_matches(user_inp_mov,titles)
print(close_movies)

['IZombie', 'Zombieland', 'Home']


In [14]:
close_movie = close_movies[0]
print(close_movie)

IZombie


In [15]:
index_pos = df_new[df_new.title == close_movie]['index'].values[0]
print(index_pos)

3601


In [16]:
similarityy_score = list(enumerate(similarity[index_pos]))
print(similarityy_score)

[(0, 0.013875496382119322), (1, 0.0491030316652342), (2, 0.046900913728178395), (3, 0.061082404925195365), (4, 0.07424482421323463), (5, 0.10854171594606112), (6, 0.02513471078206128), (7, 0.014250977463106464), (8, 0.045788275077434215), (9, 0.01455725678067543), (10, 0.0522271757880627), (11, 0.03298406326770609), (12, 0.0074920775862578086), (13, 0.035866407836438186), (14, 0.05758192010037904), (15, 0.056279743659465684), (16, 0.011885373316307103), (17, 0.0557911352445528), (18, 0.03505448935945586), (19, 0.05191426161925604), (20, 0.05507069733850653), (21, 0.05294781647712683), (22, 0.011839803534777704), (23, 0.014800961126200985), (24, 0.021425239194773172), (25, 0.06773846363138522), (26, 0.035685300485052376), (27, 0.023117312534486553), (28, 0.017872669947538434), (29, 0.03541534338644999), (30, 0.0049968543227850055), (31, 0.04468128134899947), (32, 0.0643478008550058), (33, 0.046438259249885226), (34, 0.04457228141409839), (35, 0.012431840249030924), (36, 0.00449127360832

In [17]:
sortingg = sorted(similarityy_score, key = lambda x:x[1], reverse=True)
print(sortingg)

[(3601, 1.0), (6662, 0.15112848025628747), (8803, 0.1384566422701043), (6279, 0.13319319583155903), (2190, 0.1326935149703201), (6695, 0.13236859688739466), (4632, 0.12644153408979525), (5703, 0.12504776208311408), (6318, 0.12428656965148205), (1955, 0.12058872814825736), (5352, 0.12035405651640538), (6744, 0.11840821841846666), (1873, 0.11620746258775112), (5598, 0.11438271147282156), (2303, 0.11384893815394129), (1038, 0.11183601015819841), (3789, 0.11062013966622443), (3045, 0.11014794376825056), (3624, 0.10989310015571954), (3608, 0.10944410841550652), (5, 0.10854171594606112), (8316, 0.10846432990225856), (1535, 0.10839885383212615), (5404, 0.10773007530894954), (988, 0.10769428553841116), (6264, 0.10709207491326082), (2982, 0.10598145439485321), (4772, 0.10587056886623), (6646, 0.10539662277036631), (5284, 0.1052475599991208), (390, 0.10509933878352763), (2944, 0.10434740997676739), (5569, 0.10428482847923552), (7806, 0.10403243493823194), (2526, 0.10228773865177332), (5803, 0.10

In [18]:
user_inp_mov = input("Search a Movie : ")
print("Recommended Movies")
i = 1
for moviee in sortingg:
    index = moviee[0]
    final_movies = df[df.title.index == index]['title'].values[0]
    if i<11:
        print(i,".",final_movies)
        i += 1

Search a Movie : zombie
Recommended Movies
1 . IZombie
2 . Easy A
3 . Zombie Dumb
4 . Being Mary Jane: The Series
5 . The Umbrella Academy
6 . Encounters with Evil
7 . The Good Cop
8 . Refresh Man
9 . Bitten
10 . The School Nurse Files
